### ISSUE TITLE
error initializing the extension

### ISSUE THREAD

**Issue by Userbingd** [zero01101/openOutpaint-webUI-extension#15]
I get this error when I try to launch the UI
openOutpaint init
Error loading script: main.py
Traceback (most recent call last):
  File "G:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "G:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "G:\Stable Diffusion\stable-diffusion-webui\extensions\openOutpaint-webUI-extension\scripts\main.py", line 41, in <module>
    print(run(f'"{git}" -C "' + scripts.basedir() +
  File "G:\Stable Diffusion\stable-diffusion-webui\launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "git" -C "G:\Stable Diffusion\stable-diffusion-webui\extensions\openOutpaint-webUI-extension" submodule update --init --recursive --remote
Error code: 128
stdout: <empty>
stderr: fatal: Unable to find current revision in submodule path 'app'

1 install the extension
2 launch the UI
3 fails to load
**Expected behavior**
Loading and not failing to work

- OS: Windows 10 V21H2
- GPU: GTX 1650 Super 
- Browser and Version: Firefox V108.0.1
 I don't know how to find the commits

**Comment by seijihariki** [comment]
Hm... Strange... For now, delete `extensions/openOutpaint-webui-extension/app` and restart the webui.

**Comment by Userbingd** [comment]
that seemed to fix it
