### ISSUE TITLE
[Bug]: Incompatible with the latest Automatic1111 updates

### ISSUE THREAD

**Issue by Zetaphor** [zero01101/openOutpaint-webUI-extension#46]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

Automatic1111 recently merged a large number of PR's, which included changes to the frontend, gradio version, and I believe even the API. Currently the "Send to OpenOutpaint" buttons are non-functional, and the Dream and Img2Img options are not functioning.

### Steps to reproduce the problem

1. Update Automatic1111 to the latest release (the commits start on March 25'th)
2. Attempt to send an image to the OpenOutpaint tab
3. Attempt to use the dream or img2img options

### What should have happened?

The options should have produce output. Instead they are producing console errors

### Commit where the problem happens

46534e8

### What platforms do you use to access openOutpaint?

Windows, Linux

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Browser Extensions/Addons

uBlock origin

### AUTOMATIC1111 webUI Commandline Arguments

--api --cors-allow-origins=*

### Additional information

My extensions also broke lol, the madlad merged like 40+ PR's in a single day and then they've been pushing bugfixes since

**Comment by zero01101** [comment]
hey, so the send-to buttons were definitely broken but should be fixed as of https://github.com/zero01101/openOutpaint-webUI-extension/commit/566a8a53c910f902297c4926f0d3634900403e53 - that said, the base functionality (dream/img2img) is certainly working as expected in my main webUI with a billion extensions as well as a "clean" install... what are the console errors you're getting?

**Comment by kutyadog** [comment]
The changes shown below seem to be causing issues for these colab instances:
https://github.com/zero01101/openOutpaint-webUI-extension/commit/566a8a53c910f902297c4926f0d3634900403e53

Fixed by adding:
```
!git clone https://github.com/zero01101/openOutpaint-webUI-extension /content/stable-diffusion-webui/extensions/openoutpaint-webui-extension
%cd /content/stable-diffusion-webui/extensions/openoutpaint-webui-extension
!git checkout 46534e840476dcbea4791d938f711a0d461c1ba5
```

> hey, so the send-to buttons were definitely broken but should be fixed as of [566a8a5](https://github.com/zero01101/openOutpaint-webUI-extension/commit/566a8a53c910f902297c4926f0d3634900403e53) - that said, the base functionality (dream/img2img) is certainly working as expected in my main webUI with a billion extensions as well as a "clean" install... what are the console errors you're getting?

**Comment by Zetaphor** [comment]
> hey, so the send-to buttons were definitely broken but should be fixed as of [566a8a5](https://github.com/zero01101/openOutpaint-webUI-extension/commit/566a8a53c910f902297c4926f0d3634900403e53) - that said, the base functionality (dream/img2img) is certainly working as expected in my main webUI with a billion extensions as well as a "clean" install... what are the console errors you're getting?

Testing again with the following commits:

* Automatic1111 - [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
* Openoutpaint - 566a8a53 

All other extensions disabled:

![image](https://user-images.githubusercontent.com/3112763/229214329-36798d9b-d4fb-45e2-b9d2-54c0af51f2a4.png)

Restart webui, run test prompt in txt2img, click "Send to OpenOutpaint", getting the following in the console:

```
[openoutpaint] Add message listener [openoutpaint-ext.js:117:10](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/javascript/openoutpaint-ext.js?1680291519.0955958)
[openoutpaint] Sending init message [openoutpaint-ext.js:184:11](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/javascript/openoutpaint-ext.js?1680291519.0955958)
[layers] Collection 'Image Layers' at layers.collections.image registered [layers.js:677:11](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/lib/layers.js?v=26b7436)
[layers] Layer 'Background' at layers.collections.image.layers.bg registered [layers.js:632:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/lib/layers.js?v=26b7436)
[layers] Layer 'Image' at layers.collections.image.layers.image registered [layers.js:632:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/lib/layers.js?v=26b7436)
[layers] Layer 'Mask Paint' at layers.collections.image.layers.mask registered [layers.js:632:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/lib/layers.js?v=26b7436)
[layers] Layer 'Overlay' at layers.collections.image.layers.overlay registered [layers.js:632:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/lib/layers.js?v=26b7436)
[layers] Layer 'Debug Layer' at layers.collections.image.layers.debug registered [layers.js:632:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/lib/layers.js?v=26b7436)
[commands] Running 'Initial Layer Creation'[addLayer] [commands.js:168:14](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/lib/commands.js?v=ad60afc)
[layers] Layer 'Default Image Layer' at layers.collections.image.layers.default registered [layers.js:632:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/lib/layers.js?v=26b7436)
[stamp] Connected to IndexedDB [stamp.js:651:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[openoutpaint] Sending init message [openoutpaint-ext.js:184:11](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/javascript/openoutpaint-ext.js?1680291519.0955958)
blob:http://127.0.0.1:7860/30c4b0c9-0c61-4237-a33a-8a50ff34eef5 [index.js:882:12](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/index.js?v=e10fcb1)
[webui] key.json loaded successfully [webui.js:38:11](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/webui.js?v=ccd423a)
[webui] Window is child of 'http://127.0.0.1:7860/' [webui.js:57:12](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/webui.js?v=ccd423a)
[webui] Loaded key [webui.js:77:30](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/webui.js?v=ccd423a)
[openoutpaint] Sending init message [openoutpaint-ext.js:184:11](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/javascript/openoutpaint-ext.js?1680291519.0955958)
[webui] Communication with 'http://127.0.0.1:7860/' has been initialized [webui.js:101:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/webui.js?v=ccd423a)
[index] Fixed host to 'http://127.0.0.1:7860/' [index.js:179:10](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/index.js?v=e10fcb1)
[openoutpaint] Received Init Ack [openoutpaint-ext.js:123:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/javascript/openoutpaint-ext.js?1680291519.0955958)
[stamp] Creating Resource Element [resource-03e9-939e-eef2] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-050d-0113-5a71] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-114b-4144-8a02] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-1bc8-bf37-14ff] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-203b-a5be-78d6] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-28b0-54c7-dcba] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-29e1-753d-9a88] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-2de6-36f1-e97d] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-3b5c-39b2-ee9d] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-4876-ef73-a809] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-4aaf-e4cf-e97a] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-4fab-a3a1-d759] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-55fe-e4d7-145e] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-83e0-db19-b8f9] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-8f66-5851-70b1] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-9838-13ac-857d] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-ab88-b0fa-1cf1] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-b805-9fb9-fbc1] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-c813-1b1e-a092] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-c879-57d1-fb9a] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-cbd3-c1c4-da93] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-cd74-4518-8a3d] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-e00e-5935-4234] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-e76f-d249-d8d4] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-f790-0abe-71e1] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-f90d-02ad-3ff1] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[stamp] Creating Resource Element [resource-fd51-b6fa-0019] [stamp.js:214:16](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/ui/tool/stamp.js?v=4494df6)
[index] WebUI Settings set as recommended. [index.js:1162:12](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/index.js?v=e10fcb1)
[openoutpaint] Sending init message [openoutpaint-ext.js:184:11](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/javascript/openoutpaint-ext.js?1680291519.0955958)
[webui] Communication with 'http://127.0.0.1:7860/' has been initialized [webui.js:101:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/webui.js?v=ccd423a)
[index] Fixed host to 'http://127.0.0.1:7860/' [index.js:179:10](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/index.js?v=e10fcb1)
[openoutpaint] Received Init Ack [openoutpaint-ext.js:123:15](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/javascript/openoutpaint-ext.js?1680291519.0955958)
Current model: Realism/deliberate_v2.safetensors [9aba26abdf] [index.js:1068:12](http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/index.js?v=e10fcb1)
Uncaught (in promise) TypeError: v is undefined
    ct Blocks.5efe22d4.js:76
    ze Blocks.5efe22d4.js:76
    promise callback*ze Blocks.5efe22d4.js:76
    to Blocks.5efe22d4.js:76
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    _ Button.svelte:12
    zr index.37b24c07.js:4
    zr index.37b24c07.js:4
    c Button.svelte:11
    Le index.37b24c07.js:1
    m Button.svelte:16
    ue index.37b24c07.js:4
    m Button.svelte:21
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Row.svelte:11
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Column.svelte:14
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
    m Column.svelte:14
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    ue index.37b24c07.js:4
    m Blocks.5efe22d4.js:31
    m Blocks.5efe22d4.js:31
[Blocks.svelte:214:2](http://127.0.0.1:7860/ui/packages/app/src/Blocks.svelte)

​
```

**Comment by Zetaphor** [comment]
Same setup, reload webui, go to OpenOutpaint tab and attempt to dream with "test prompt" and same DeliberateV2 model loaded:

![image](https://user-images.githubusercontent.com/3112763/229214861-ab1324e4-9dab-46b8-b380-ee62d477fcb0.png)

500 error on http://127.0.0.1:7860/sdapi/v1/txt2img
```
{"error":"RuntimeError","detail":"","body":"","errors":"There is no current event loop in thread 'AnyIO worker thread'."}
```

HAR link: https://drive.google.com/file/d/1p9l52kdWbXfOQfxgzJwg0j3d16MZ9yAN/view?usp=share_link

**Comment by Zetaphor** [comment]
Same process, response from Img2Img:

```
{"error":"RuntimeError","detail":"","body":"","errors":"There is no current event loop in thread 'AnyIO worker thread'."}
```

**Comment by Zetaphor** [comment]
Just to be safe I also nuked the extension folder and did a fresh checkout, same issues present

**Comment by Zetaphor** [comment]
I also have a separate installation of Automatic1111 that is locked in at the pre-March 25'th commits where it works perfectly fine. That is where this installation came from, I duplicated that folder and then did a git pull to setup the second installation

**Comment by zero01101** [comment]
@kutyadog yeah, apologetically i have like almost no familiarity with colabs in general for the most part, but if a previous version of the extension works better for that there's actually a commandline flag specifically for those instances - just add ` --lock-oo-submodule` to your launch flags and it'll disable the submodule update checks.  that commit's the last one that had the tags for any versions of webUI prior to the new gradio changes

@Zetaphor i can confirm that svelte throws up an error about v being null in web console but the extension still works as expected and i have _no clue_ where to even start with minimized gradio lol; have you seen [this issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9046)?  could you try going to http://127.0.0.1:7860/docs#/default/text2imgapi_sdapi_v1_txt2img_post, click `try it out` and populate the request body input with

**Comment by Zetaphor** [comment]
Apologies for the delay @zero01101, looks like that's also failing on the server side:

![image](https://user-images.githubusercontent.com/3112763/229607548-7b6c099a-ec08-4f98-a3dc-d3da6dd2c975.png)

**Comment by Zetaphor** [comment]
It also fails with the default parameters, looks like the API is busted for some reason?

**Comment by zero01101** [comment]
yeah, there's https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9319 open right now to deal with that, but openOutpaint definitely relies on the API functionality to be operational.  tested send-to buttons on native linux as well which also work as expected on current commits for webUI, openOutpaint, and oo-extension so this is all seeming to point at colab vs webUI updates

**Comment by Zetaphor** [comment]
Strange, I'm running on Linux, not colab or docker. I guess I'll try reinstalling from the latest commit

**Comment by 253189147cc** [comment]
Hi bro, thanks a lot for the excellent work. I thought  outpainting was cool but never had success using it. I am using automatic1111 colab version, I read the instructions carefully and know that the code --api is added to the web user.sh file, but every time after saving it, the --api disappears when I start it again, so it never works, how should I do it?

**Comment by Raivshard** [comment]
Has there been any progress with this? I still can't run it in automatic, and the same issue seems to exist with vlad diffusion

**Comment by zero01101** [comment]
terribly sorry for the extended delay; this project isn't abandoned but i've had to step away from it due to Reasons for a while, and i admit additional responses may (aka will probably) be delayed but hopefully not nearly as long

@253189147cc thanks for the kind words; i think that's a separate issue to the topic at hand, but i believe there's a different way of enabling API on colabs?  looking at https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb it appears to be enabled by default in the bottom block? 

![image](https://github.com/zero01101/openOutpaint-webUI-extension/assets/1649724/7e3768fc-a0fe-4717-b824-baaaf856436c)

@Raivshard i can definitely at least confirm that base functionality should still work almost seamlessly in chrome/chromium-based browsers, and firefox just needs to get kicked in the refresh button on the openOutpaint tab to fire up on both windows and linux hosted instances, but is still kind of frustrating... i tried the extension in vlad's fork like RIGHT when the whole dustup was starting and it worked out of the box, but that was also about when i had to step back for a bit so things may have changed since then.  

are you getting any particular errors in f12 console logs or webUI console?  does the [txt2img API test](https://github.com/zero01101/openOutpaint-webUI-extension/issues/46#issuecomment-1492666692) mentioned above pass?

**Comment by Raivshard** [comment]
If you had asked me this a couple of weeks ago, the answer would have been no, which is why I removed the extension in the first place, but it does seem to work now. Nice.
